services:
  payment:
    build: .
    container_name: payment_api
    ports:
    - "8000:8000"
    volumes:
    - ./:/app
    environment:
    - API_KEY=abc_dev_UNdBUnfUbf1z4Mh2Y2twc4jQ
    - SECRET_KEY='66ççpp'
    - MONGO_URL=mongodb+srv://gabrielvlnt:Torreogo.12@paymentapi.lx4xcuv.mongodb.net/?retryWrites=true&w=majority&appName=paymentapi


