name: PaymentAPI CI/CD
on:
  push:
    branches: [main]
    paths:
      - 'paymentAPI/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: payment-api

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./payment-api/paymentAPI

      - name: Run tests
        run: |
          python -m pytest
        working-directory: ./payment-api/paymentAPI

      - name: Debug on failure
        if: failure()
        run: |
          ls -la tests/
          cat requirements.txt
        working-directory: ./payment-api/paymentAPI
