name: PaymentAPI CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start services with docker-compose
        run: |
          docker-compose -f docker-compose.yaml up -d

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yaml exec -T app python -m pytest |
          test_service.py

      - name: Stop services
        run: |
          docker-compose -f docker-compose.yaml down
